services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    expose:
      - "8080"  # Internal only
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/todo_db

  frontend:
    build: ./frontend
    expose:
      - "80"  # Internal only
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # External access on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data: